version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/cloudflare/cloudflare-go
    versions:
    - 0.14.0
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
