image: golang:alpine
before_script:
  - apk --update add git

stages:
  - test
  - release

test:
  stage: test
  variables:
    CGO_ENABLED: 0
  script:
    - go vet ./...
    - go test ./...

# release:
#   stage: release
#   script:
#     - GOOS=darwin GOARCH=amd64 go build
#     - GOOS=linux GOARCH=amd64 go build
#     - GOOS=linux GOARCH=386 go build
#     - GOOS=linux GOARCH=arm go build
#     - GOOS=linux GOARCH=arm64 go build
#     - GOOS=freebsd GOARCH=amd64 go build
#     - GOOS=openbsd GOARCH=amd64 go build
#     - GOOS=windows GOARCH=386 go build
#     - GOOS=windows GOARCH=amd64 go build
#   only:
#     - tag
